// Generates responsive WebP derivatives for the local product photos.
//
// The 46 products shipped in this repo point at JPEGs under
// public/products/ (1000×1250, 40–430KB each). Cloudinary handles format
// and resizing for every image uploaded through the admin panel, but these
// local files get none of that — so before this script, every product card
// downloaded the full 1000px JPEG to render a ~350px thumbnail.
//
// For each public/products/**/*.jpg this writes <name>-400.webp,
// <name>-700.webp and <name>-1000.webp beside the original. The originals
// are untouched and remain the <img src> fallback. Derivatives are build
// output (gitignored) and regenerated by `npm run build`; a derivative is
// skipped when it's already newer than its source, so re-runs are cheap.
//
// Usage: node scripts/optimize-images.mjs   (or `npm run images`)

import { readdir, stat } from "node:fs/promises";
import { join, extname, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "public", "products");
// The shop photos are 1000px wide; never advertise a width the source lacks.
export const WIDTHS = [400, 700, 1000];
const QUALITY = 78;

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (/\.jpe?g$/i.test(entry.name)) yield full;
  }
}

async function isFresh(src, out) {
  try {
    const [s, o] = await Promise.all([stat(src), stat(out)]);
    return o.mtimeMs >= s.mtimeMs;
  } catch {
    return false;
  }
}

let written = 0;
let skipped = 0;
let inputBytes = 0;
let outputBytes = 0;

for await (const src of walk(ROOT)) {
  const base = join(dirname(src), basename(src, extname(src)));
  const meta = await sharp(src).metadata();
  inputBytes += (await stat(src)).size;

  for (const w of WIDTHS) {
    const out = `${base}-${w}.webp`;
    if (await isFresh(src, out)) {
      skipped++;
      outputBytes += (await stat(out)).size;
      continue;
    }
    // withoutEnlargement: never upscale a small original — the srcSet
    // would then advertise pixels that don't exist.
    const info = await sharp(src)
      .resize({ width: Math.min(w, meta.width ?? w), withoutEnlargement: true })
      .webp({ quality: QUALITY })
      .toFile(out);
    outputBytes += info.size;
    written++;
  }
}

const mb = (n) => (n / 1048576).toFixed(2);
console.log(
  `[images] ${written} written, ${skipped} up to date · originals ${mb(inputBytes)} MB → all derivatives ${mb(outputBytes)} MB`,
);
